global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "wordpress_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # Commented out services that don't have built-in metrics endpoints
  # - job_name: 'wordpress'
  #   static_configs:
  #     - targets: ['wordpress:80']
  #   metrics_path: '/wp-content/plugins/prometheus-exporter/metrics'
  #   scrape_interval: 30s

  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx:80']
  #   metrics_path: '/nginx_status'
  #   scrape_interval: 30s

  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-master:3306', 'mysql-slave:3306']
  #   scrape_interval: 30s

  # - job_name: 'memcached'
  #   static_configs:
  #     - targets: ['memcached:11211']
  #   scrape_interval: 30s
